/**
 * Environment Setup Command
 * Interactive wizard for setting up .env.local
 */

import chalk from 'chalk';
import inquirer from 'inquirer';
import fs from 'fs/promises';
import path from 'path';

interface EnvOptions {
  skipSupabase?: boolean;
  skipAmadeus?: boolean;
  skipOpenai?: boolean;
}

export async function setupEnvCommand(options: EnvOptions) {
  console.log(chalk.blue.bold('\n⚙️  Environment Setup Wizard\n'));

  const envPath = path.join(process.cwd(), '.env.local');

  const questions: any[] = [];

  if (!options.skipSupabase) {
    questions.push(
      {
        type: 'input',
        name: 'supabaseUrl',
        message: 'Supabase Project URL:',
        validate: (input: string) => input.length > 0 || 'Required'
      },
      {
        type: 'input',
        name: 'supabaseAnonKey',
        message: 'Supabase Anon Key:',
        validate: (input: string) => input.length > 0 || 'Required'
      }
    );
  }

  if (!options.skipAmadeus) {
    questions.push(
      {
        type: 'input',
        name: 'amadeusKey',
        message: 'Amadeus API Key:',
      },
      {
        type: 'input',
        name: 'amadeusSecret',
        message: 'Amadeus API Secret:',
      }
    );
  }

  if (!options.skipOpenai) {
    questions.push({
      type: 'input',
      name: 'openaiKey',
      message: 'OpenAI API Key:',
    });
  }

  const answers = await inquirer.prompt(questions);

  // Build .env content
  let envContent = '# Generated by Wingman CLI\n\n';

  if (answers.supabaseUrl) {
    envContent += `NEXT_PUBLIC_SUPABASE_URL=${answers.supabaseUrl}\n`;
    envContent += `NEXT_PUBLIC_SUPABASE_ANON_KEY=${answers.supabaseAnonKey}\n\n`;
  }

  if (answers.amadeusKey) {
    envContent += `AMADEUS_API_KEY=${answers.amadeusKey}\n`;
    envContent += `AMADEUS_API_SECRET=${answers.amadeusSecret}\n`;
    envContent += `FLIGHT_API_MODE=amadeus\n\n`;
  }

  if (answers.openaiKey) {
    envContent += `OPENAI_API_KEY=${answers.openaiKey}\n\n`;
  }

  envContent += `CRON_SECRET=${generateRandomSecret()}\n`;

  // Write .env.local
  await fs.writeFile(envPath, envContent, 'utf-8');

  console.log(chalk.green.bold('\n✅ Environment configuration saved to .env.local\n'));
  console.log(chalk.cyan('Next steps:'));
  console.log('  1. Review your .env.local file');
  console.log('  2. Add any missing environment variables');
  console.log('  3. Start the development server: npm run dev\n');
}

function generateRandomSecret(): string {
  return Array.from({ length: 32 }, () =>
    Math.floor(Math.random() * 16).toString(16)
  ).join('');
}
